### ISSUE TITLE
Error: Modifier is already applied on this attribute!

### ISSUE THREAD

**Issue by judgekreep** [Meldexun/ReachFix#1]
I turned my friend into creative, then a minute later I turned myself into creative - that's when I got the error the first time.
I turned myself back to survival (no error) then turned my friend back to survival (got the error a second time).

If relevant, we weren't near each other (probably about 10 chunks away from each other).

Crash report:
https://pastebin.com/bsfPYAk5

`ReachFix-1.12.2-1.0.1`
This occurred with a custom mod pack.

**Comment by Meldexun** [comment]
Fixed in v1.12.2-1.0.2
