### ISSUE TITLE
1.16.5 - Incompat w/ Immersive Engineering

### ISSUE THREAD

**Issue by PhweeDev** [Meldexun/ReachFix#4]
When using the game w/ Immersive Engineering. The game will crash.

Take a look.

https://paste.gg/p/anonymous/7f2327bda9a942a2953ac472fb4fc7fb

**Comment by Meldexun** [comment]
I'm unable to reproduce this. Can you give me exact steps to reproduce the issue?

**Comment by PhweeDev** [comment]
Create a completely fresh instance and install only Immersive Engineering and Reach Fix.

**Comment by Meldexun** [comment]
Now I was able to reproduce it for some reason.
Anyway this is fixed in v1.16.5-1.0.1
