### ISSUE TITLE
[1.12.2] Crash: Modifier is already applied on this attribute!

### ISSUE THREAD

**Issue by judgekreep** [Meldexun/ReachFix#6]
**Describe the bug**
Related to #1; I receive a crash report that says, "modifier is already applied on this attribute!"
I was playing on a LAN server with 2 other players, and we were all in survival mode.
One player mentioned that he was putting some enchanted items inside of a chest, other than that, everything going on at that time was pretty unsuspicious.

**To Reproduce**
I have been unable to pinpoint what causes this issue. It's happened twice today but I was unable to reproduce it after the second time.

**Screenshots/Videos**
N/A

**Versions**
Reach Fix: 1.12.2-1.0.5
Forge: 14.23.5.2860
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug): 

**Log File**
Please use a paste site to upload the log file (for example https://gist.github.com/) and provide the link to the file here:
https://gist.github.com/platinumphoenix2/f9ea27bb1c023692d6535c8b9e5d5bd1

**Comment by Meldexun** [comment]
Please provide an up to date log. This one is from Jan 2022 and uses v1.0.1

**Comment by judgekreep** [comment]
I apologize for wasting your time.
It turns out that I sorted the crash reports by date and assumed this one was the relevant crash log without looking at the date.

My eyes always go straight to the report itself and never at the date - at least one of us was observant enough to catch that.
I'll be sure to review the other details before submitting any crash reports in the future. Again, I apologize!
