### ISSUE TITLE
Incompatible with Spartan Weaponry

### ISSUE THREAD

**Issue by Kasualix** [Meldexun/ReachFix#8]
**Describe the bug**
Weapons in Spartan Weaponry that increase player reach distance can't increase it anymore with ReachFix.
![image](https://github.com/Meldexun/ReachFix/assets/110756250/567a8331-5393-4493-b3c6-75fd34b68ff4)

**To Reproduce**
1. install Spartan Weaponry, launch the game, create a new world
2. pick up a Diamond Pike in creative inventory
3. summon and target a vindicator to show the crosshair indicator by max reach distance (don't attack it)
4. save the world, exit the game
5. install ReachFix, launch the game
6. enter the former world
7. the crosshair indicator disappears

{NoAI:1} would be helpful if you find the summoned vindicator walks randomly.

**Screenshots/Videos**
Spartan Weaponry without ReachFix
![image](https://github.com/Meldexun/ReachFix/assets/110756250/ab2f3173-6140-4f01-bb85-df04a16772bd)
Spartan Weaponry with ReachFix
![image](https://github.com/Meldexun/ReachFix/assets/110756250/2a68fbf9-014a-4e1b-995b-234d3693e7f3)

**Versions**
Reach Fix: 1.0.1
Forge: 36.2.39
Minecraft: 1.16.5
Other mods (necessary to reproduce the bug): Spartan Weaponry

**Log File**
https://pastebin.ubuntu.com/p/KSRxNsKQFn/
I don't think log would contain valid info XD

**Comment by Meldexun** [comment]
I tested SpartanWeaponry-1.16.5-2.2.0-rc-2 without any other mods and the reach increasing properties don't work at all. Aside from that the attack indicator seems to be buggy as well and instead I tried actually attacking the enemy for my test.

This means this is an issue of SpartanWeaponry and not ReachFix.
